unbind r
bind r so ~/.tmux.conf
set -g status-interval 5               # set update frequencey (default 15 seconds)
set -g status-justify centre           # center window list for clarity
set-option -g status-style bg=default
set-option -g status-position top
set-option -a terminal-overrides ",*256col*:RGB"
# fix error
set-option -sg escape-time 10
set-option -g focus-events on
set-option -g default-terminal "screen-256color"

set -g status-left "#[fg=magenta] #[bg=gray][#S]"
set -g window-status-current-format "#[fg=black, bg=default]│#[fg=magenta, bg=gray]#W#[fg=black,bg=default]│"
set -g status-right "#[fg=magenta, bg=gray] #{=|-24|…;s|$HOME|~|:pane_current_path}"
# title
set-option -g set-titles on
set -g allow-rename on

# vi mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind P paste-buffer

bind-key h select-pane -L
bind-key j select-pane -D
bind-key l select-pane -R


bind-key k select-pane -U
